ktor:
    application:
        modules:
            - jp.ac.it_college.std.s24016.kotlin.ktor.examole.ApplicationKt.module
    deployment:
        port: 8080

database:
    url: jdbc:postgresql://localhost:5432/exposed_example
    driver: org.postgresql.Driver
    user: exposed
    password: kotlin